
# ä½œè€…ä¿¡æ¯
boy:
  name: Bridge #ç”·ç”Ÿæ˜µç§°
  avatar: 
girl:
  name: Dream #å¥³ç”Ÿæ˜µç§°
  avatar: 

#å¯¼èˆªæ¡
menu:
  ğŸš©åšå®¢: https:///bridgeofdream.xyz/
  ğŸ’æƒ…ä¾£: https://bridgeofdream.xyz/sweetcloud
  #é¡µé¢åç§°: é¡µé¢åœ°å€



# å“”å“”è®¾ç½® â˜†å¿…é¡»
#ç”·ç”Ÿçš„å“”å“”
boybb:
  appId: HKXdavvMmcGwQssPCOi4nGDp-MdYXbMMI
  appKey: 0cU5vqlzDr9vycjbdjx19jjl
  serverUrl: https://hkxdavvm.api.lncldglobal.com

#å¥³ç”Ÿçš„å“”å“”
girlbb:
  appId: HKXdavvMmcGwQssPCOi4nGDp-MdYXbMMI
  appKey: 0cU5vqlzDr9vycjbdjx19jjl
  serverUrl: https://hkxdavvm.api.lncldglobal.com


# ç›¸æ‹çºªå¿µæ—¥
anniversary: '2018-12-14'

# ç™¾åº¦ç»Ÿè®¡
#baidu_analytics_key: # 5fb5fd0062e816d3a3ca2dacf095bc0f